[2021-08-23 23:21:09 +0800] [29409] [INFO] Starting gunicorn 20.1.0
[2021-08-23 23:21:09 +0800] [29409] [INFO] Listening at: http://0.0.0.0:8080 (29409)
[2021-08-23 23:21:09 +0800] [29409] [INFO] Using worker: sync
[2021-08-23 23:21:09 +0800] [29412] [INFO] Booting worker with pid: 29412
[2021-08-23 23:21:09 +0800] [29412] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/Cinema_Tickets_Booking_System/Server/user_login.py", line 1, in <module>
    from flask import Flask, redirect, url_for, request
ModuleNotFoundError: No module named 'flask'
[2021-08-23 23:21:09 +0800] [29412] [INFO] Worker exiting (pid: 29412)
[2021-08-23 23:21:09 +0800] [29409] [INFO] Shutting down: Master
[2021-08-23 23:21:09 +0800] [29409] [INFO] Reason: Worker failed to boot.
1
